### PR TITLE
Use micromatch to handle Win path sep

### LINKED ISSUE #642: Cannot read property 'locale' of null for `@lingui/loader`
**Describe the bug**
App crashes when using `@lingui/loader`

**To Reproduce**
Install deps and run example of `create-react-app` from `next` branch.

**Expected behavior**
It should work :)

**Additional context**
image

It's coming from this line. Apparently the `getCatalogForFile` returns `null` for some reason. I will investigate it further, but I suspect it's a classic issue of wrong path separators (I am on Windows).

https://github.com/lingui/js-lingui/blob/24d521ff385647f69f73188fd35e07079efdc1f3/packages/loader/src/index.js#L41

- jsLingui version ``lingui --version``: 3.0.0-10

### PR DESCRIPTION
**Pull request by FredyC**
Fixes #642

### CODE REVIEW

**Comment by FredyC** [comment]
Not sure why tests are failing with this change, apparently there are duplicate `@types/react` packages. I have good experience with `npx yarn-deduplicate -s fewer yarn.lock` to fix that.

Also, you said that Appveyor tests are ok, but since they are only running build then it's obvious. It should also run tests and then you would see anything related to Windows path failing due to snapshot testing.

**Comment by FredyC** [comment]
Hm, looks like that `micromatch` is also a piece of crap. When it gets Windows path, it fails too. I guess I will just approach it differently and try to normalize any path to POSIX format instead of relying on these weird tools.

**Comment by tricoder42** [comment]
> Also, you said that Appveyor tests are ok, but since they are only running build then it's obvious. It should also run tests and then you would see anything related to Windows path failing due to snapshot testing.

Ups, good point. I'll fix it. 

> Btw that failing linter check should be easily fixable by running npx yarn-deduplicate -s fewer yarn.lock. Duplicate types packages are evil :)

Yeah, my bad. I've fixed `yarn.lock` last night with `npx yarn-deduplicate` but forgot to commit... It's already in `next` branch and CI build is green.

**Comment by FredyC** [comment]
This is harder than it looks, I will get back to it later today.

**Comment by tricoder42** [comment]
Yeah, this is tricky. I'm having fun with #644 myself.

I think we should convert all paths to POSIX as soon as possible (e.g. when catalog is created) and internally use only POSIX. If `minimatch` or other glob library supports it, then this is the way to go. Otherwise we'll have more troubles down the line, especially with snapshot testing.

For example, message origins are always converted to POSIX paths - that way message catalogs are the same no matter if you extract them on win or other system.

**Comment by FredyC** [comment]
So, should I close this PR? Because you seem to be solving the same thing in #644. Not sure why such double work.

**Comment by FredyC** [comment]
Although I took a bit different approach. Perhaps if you have other work, I can figure it out in catalogs and then you can continue with Appveyor.

**Comment by FredyC** [comment]
@tricoder42 I think it's ready now, tests are passing on WIndows as well, at least for catalog. I skipped other test files :)

The test `Catalog make should collect and write catalogs` gave me a hard time because some other test writes to a real file system without the cleanup and this one reads it making test extremely flaky locally.

**Comment by tricoder42** [comment]
> So, should I close this PR? Because you seem to be solving the same thing in #644. Not sure why such double work.

I just wanted to enable tests in Appveyor and fix any related problems. The I realized that all failing tests are the ones you're trying to fix, so I stepped aside and waited.

> I skipped other test files :)

I don't see any skipped tests. Everything looks good. Great job!

**Pull request merged**
