### PR TITLE
feat: allow comment prop on react Trans component

### PR DESCRIPTION
**Pull request by j4hr3n**
Tested by publishing to Verdaccio and installing in a project of mine. Worked like a charm. The React Trans tests even use comment in `jsx-without-macros.js`.

# Description

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

https://github.com/lingui/js-lingui/issues/1713

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thekip** [comment]
Please add a separate test case for that. This will ensure it will not break in future or someone will not change this functionality.

**Comment by j4hr3n** [comment]
> Please add a separate test case for that. This will ensure it will not break in future or someone will not change this functionality.

@thekip where would you like me to add a test for this?

**Comment by thekip** [comment]
@j4hr3n i've just checked, there is already a test for comment in Trans component. So just ignore my previous comment.

**Review by thekip — APPROVED** [review]

**Review by andrii-bodnar — APPROVED** [review]
@j4hr3n thank you!

**Pull request merged**
