### PR TITLE
Order extracted messages alphabetically by message ID

### PR DESCRIPTION
**Pull request by queicherius**
This is my try to implement #229.

- I did not work with ramda before, so I am sure there is a better way to implement `orderByMessageId`.
- Only a part of the tests ran locally for me, so I'm going to see what CI says
- I also did not test the actual output of the built command, since the build failed for me locally
- Feel free to completely discard this if there is a better way to implement it 😄

### CODE REVIEW

**Comment by tricoder42** [comment]
> I did not work with ramda before, so I am sure there is a better way to implement orderByMessageId.

Me neither, looks good!

> I also did not test the actual output of the built command, since the build failed for me locally.

How the build failed? Would you like to share the output?

> Feel free to completely discard this if there is a better way to implement it 

No, it's awesome! Thanks, going to merge and release it soon.

**Comment by queicherius** [comment]
Thanks for merging! :) Looking forward to this.

> How the build failed? Would you like to share the output?

I use Linux for windows, and sometimes builds just fail for me on that setup. I attached the output of `node ./scripts/test.js` here: [test-output.txt](https://github.com/lingui/js-lingui/files/2130660/test-output.txt)

**Comment by tricoder42** [comment]
Fixed and released in [v2.2.0](https://github.com/lingui/js-lingui/blob/stable-2.x/CHANGELOG.md#220-2018-07-04). Thanks to all involved!

**Comment by tricoder42** [comment]
@queicherius hmm, weird. This looks like something in lodash or probably lodash/windows combination :/

**Pull request merged**
