### PR TITLE
refactor(build): migrate to unbuild

### PR DESCRIPTION
**Pull request by thekip**
# Description

All packages except `@lingui/cli` smoothly migrated to unbuild. 
I also installed and used yarn workspaces plugin which allows running tasks over monorepo in parallel and topological order (deps first)

I'm going to migrate  `@lingui/cli` to unbuild in next iterations and delete old build scripts. This PR already have 50+ files changed. 

Other issue: 

`@lingui/core/compile` feels like a weird hack. Let me remind why its here. We have `@lingui/core` which has conditional (under `if`) import for `@lingui/core/compile`. This was needed to satisfy modern bundlers and let them tree shake this from the final bundle on production. 
But requiring itself feels very uncommon and error-prone. I recommend extracting it into separate package `@lingui/compile-message` and use it from all places. I don't see other options, this would be straightforward and future-proof. 

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thekip** [comment]
The codecov again showing a weather

**Comment by thekip** [comment]
rebased

**Comment by andrii-bodnar** [comment]
> The codecov again showing a weather

It's strange because codecov behaves well when there are no merges into the `main` (the `next` is default now on its side). There were no problems with coverage for all the recent PRs

**Comment by thekip** [comment]
Try to restart the WF

**Comment by andrii-bodnar** [comment]
It didn't help. If to compare code coverage on the `next` branch and on the current branch, there is a big difference for the `core`, `macro`, and `react` packages.

It might be caused by the `testEnvironment` change.

The `next` branch coverage: https://app.codecov.io/gh/lingui/js-lingui/tree/next/packages

The current branch coverage: https://app.codecov.io/gh/lingui/js-lingui/tree/migrate-to-unbuild/packages

**Comment by thekip** [comment]
It gathered coverage from ./dist instead of sources, so actual sources were not taken into report. I fixed (i hope)

**Comment by thekip** [comment]
Something went wrong, WF hangs for more than 1 hour for now. @andrii-bodnar could you stop them and try to rerun. Other WF today also behaved weird, maybe it's related.

**Comment by andrii-bodnar** [comment]
Restarted and had to cancel since it was hanging again

**Review by andrii-bodnar — APPROVED** [review]

**Pull request merged**
