### PR TITLE
fix: windows compatibility

### PR DESCRIPTION
**Pull request by thekip**
# Description

i installed Windows ARM on my Mac, and fixed all compatibility issues which were marked as "skipOnWindows" in tests.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Examples update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Comment by yunsii** [comment]
Is it will fix this issue https://github.com/lingui/js-lingui/issues/1793?

**Comment by thekip** [comment]
no

**Comment by thekip** [comment]
I hope so. I found that path issues on windows become even more weird when inter-disc execution is involved. For example, code working perfectly when it stored on disk C, but then suddenly become broken when you just move it to the disk D. 

There is also no way to express a relative path between these two disks, and not every tool understand an absolute windows paths.

**Comment by yunsii** [comment]
> but then suddenly become broken when you just move it to the disk D.

I always think the comment is relative path in git repo, why related the inter-disc execution? 😦

**Comment by thekip** [comment]
Exactly, it should be relative to the rootDir specified in the lingui config. And that the goal i wanted to achieve, so no matter where files are stored result should be the same. But on windows, it turned out that it might be broken due to where files are stored, which is weird. 

The inter disc execution happened in experimental extractor. Previously, it used `os.tmpDir()` to store esbuild generated bundles. On windows it's always would be on the system disk (C:) and if you code stored on disk D: esbuild not able to generate a correct relative path to sources, and then lingui extractor could not make this path relative to rootDir.

**Comment by yunsii** [comment]
Is it possible to make lingui extractor always use same disk (maybe C:) to parse relative path?

**Comment by thekip** [comment]
That exactly what i did in this PR, among other things

**Review by andrii-bodnar — APPROVED** [review]
@thekip thank you!

**Comment by bravo-kernel** [comment]
This is great, much appreciated 👏

**Pull request merged**
