### PR TITLE
Ensure render of I18nProvider in async scenarios

### PR DESCRIPTION
**Pull request by Bertg**
This is related to #834

This PR solves 2 issues:

* Making sure the component gets re-rendered when needed
* Provide a warning to the developer

Some more thoughts about this PR and problem:

* It is perfectly possible for the warning to appear even if the component will render. 
* It would be better to always render. We can add a warning to the developer that only defaults will be rendered. This requires the developer to make sure a language is activated before they render the component. We could even choose to completely throw if i18n is not activated yet, unless the developer set a prop indicating they are OK with defaults.
* ```forceRenderOnLocaleChange``` should be separated from ```dontRenderIfNoLocaleIsActivated```
* ideally there should be a ```i18n.on("activated" ``` which also triggers when first observed (if already triggered before). That way the extra call to ```setRenderKey``` in the effect is never needed.

### CODE REVIEW

**Comment by tricoder42** [comment]
Perfect, thanks!

> ideally there should be a i18n.on("activated" 

Let's try it as it is and figure out how to improve it later. I guess we could add a signal `activated` or `loaded` which would be triggered after message catalog for active locale is loaded and available.

**Comment by Bertg** [comment]
Quick question... may I be added to the contributor list? :)

**Comment by tricoder42** [comment]
@Bertg I don't think we have an explicit list of contributors 🤔  The [contributors](https://github.com/lingui/js-lingui#contributors) section in README is generated automatically from [repository contributors](https://github.com/lingui/js-lingui/graphs/contributors). I guess it's just cached and you should appear there in few days.

And if I haven't said it explicitly, thank you for your help! I really appreaciate everyone who's willing to spend their free time contributing to this project 🙏

**Comment by Bertg** [comment]
You're welcome :)

Actually felt kind of embarrassed asking, but this is a project I would be proud of having my name attached to.

**Comment by tricoder42** [comment]
Yeah, this is a valid point 👍  We could use GitHub Action to automatically generate list of contributors after each pull request. I'm gonna check it later. GitHub Actions are really powerfull 🚀

**Pull request merged**
