### PR TITLE
feat(format-po-gettext): respect Plural-Forms header

### PR DESCRIPTION
**Pull request by timofei-iatsenko**
# Description

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Examples update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Comment by garikkh** [comment]
Also some uncaught runtime errors if the locale isn't found in the cldr plurals lib.

Probably needs a cleaner error message, and also specifically for `pseudo` case. Following [this guide](https://lingui.dev/guides/pseudolocalization) there is this runtime error:

```
yarn i18n:compile                       
Compiling message catalogs…
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

RethrownError: Cannot read /home/MY_PROJECT/I18N/pseudo/lingui.po 
Original: TypeError: Cannot read properties of null (reading 'length')
    at getPluralCases (/home/MY_PROJECT/node_modules/@lingui/format-po-gettext/dist/po-gettext.cjs:22625:66)
    at Object.parse (/home/MY_PROJECT/node_modules/@lingui/format-po-gettext/dist/po-gettext.cjs:22722:25)
    at FormatterWrapper.read (/home/MY_PROJECT/node_modules/@lingui/cli/dist/api/formats/formatterWrapper.js:32:27)
    at async Catalog.read (/home/MY_PROJECT/node_modules/@lingui/cli/dist/api/catalog.js:153:16)
    at async /home/MY_PROJECT/node_modules/@lingui/cli/dist/api/catalog.js:157:77
    at async Promise.all (index 12)
    at async Catalog.readAll (/home/MY_PROJECT/node_modules/@lingui/cli/dist/api/catalog.js:157:9)
    at async getTranslationsForCatalog (/home/MY_PROJECT/node_modules/@lingui/cli/dist/api/catalog/getTranslationsForCatalog.js:6:22)
    at async Catalog.getTranslations (/home/MY_PROJECT/node_modules/@lingui/cli/dist/api/catalog.js:123:16)
    at async command (/home/MY_PROJECT/node_modules/@lingui/cli/dist/lingui-compile.js:26:30) {
  message: "Cannot read /home/MY_PROJECT/I18N
```

**Comment by timofei-iatsenko** [comment]
@garikkh could you take it over and finish this PR?

**Comment by garikkh** [comment]
Had a few fixes here: https://github.com/timofei-iatsenko/js-lingui/compare/feature/respect-plural-forms-header...garikkh:js-lingui:feature/respect-plural-forms-header

tested the PO files my TMS generates, looks good.

One thing to note is that because the library uses `Intl.PluralRules` it technically isn't going to respect the `Plural-forms` header. `Intl.PluralRules` use CLDR plurals for which form to select. The benefit of this PR is that you can define either the gettext plural form or the CLDR plural form, and both will work. 

Another note: I considered using either https://www.npmjs.com/package/cldr or https://www.npmjs.com/package/cldr-data instead of having to copy/paste a json file, but both were just as silly to use for this case.

**Comment by garikkh** [comment]
@andrii-bodnar I linked a PR I made with @timofei-iatsenko fork as the base branch, just so it was a tiny bit neater. Wasn't sure if you guys wanted a separate PR. 

https://github.com/timofei-iatsenko/js-lingui/pull/1

> I also feel that committing these rules in raw format might not be the best approach. It might be more efficient and manageable to use a dependency for this instead.

Agreed but the one being used here doesn't export the JSON and the maintainer doesn't want to add it to their exports. I don't remember the exact issues with the other two, so I could check again.

**Comment by garikkh** [comment]
More details:

cldr-data is a great repository, but the plurals data is difficult to parse. each language has plurals defined like this:

```json
      "cs": {
        "pluralRule-count-one": "i = 1 and v = 0 @integer 1",
        "pluralRule-count-few": "i = 2..4 and v = 0 @integer 2~4",
        "pluralRule-count-many": "v != 0   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …",
        "pluralRule-count-other": " @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …"
      },
```

And not exactly great to parse and extract actual samples from. 


`cldr` is also same; its intended to be used with just the plural forms and the function:

```js
> cldr.extractPluralClasses("cs")
[ 'one', 'few', 'many', 'other' ]
> cldr.extractPluralRuleFunction("cs")(1)
'one'
> cldr.extractPluralRuleFunction("cs")(100)
'other'
```

But other than that only provides raw xml for data:

```xml
<pluralRules locales="cs sk">
    <pluralRule count="one">i = 1 and v = 0 @integer 1</pluralRule>
    <pluralRule count="few">i = 2..4 and v = 0 @integer 2~4</pluralRule>
    <pluralRule count="many">v != 0   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …</pluralRule>
    <pluralRule count="other"> @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …</pluralRule>
</pluralRules>
```

And for the forms:

```xml
<pluralRanges locales="cs pl sk">
	<pluralRange start="one"   end="few"   result="few"/>
	<pluralRange start="one"   end="many"  result="many"/>
	<pluralRange start="one"   end="other" result="other"/>
	<pluralRange start="few"   end="few"   result="few"/>
	<pluralRange start="few"   end="many"  result="many"/>
	<pluralRange start="few"   end="other" result="other"/>
	<pluralRange start="many"  end="one"   result="one"/>
	<pluralRange start="many"  end="few"   result="few"/>
	<pluralRange start="many"  end="many"  result="many"/>
	<pluralRange start="many"  end="other" result="other"/>
	<pluralRange start="other" end="one"   result="one"/>
	<pluralRange start="other" end="few"   result="few"/>
	<pluralRange start="other" end="many"  result="many"/>
	<pluralRange start="other" end="other" result="other"/>
</pluralRanges>
```

**Pull request closed without merging**
