### PR TITLE
feat(macro): Add support for passing custom i18n instance

### PR DESCRIPTION
**Pull request by jeroenvisser101**
This allows developers that work in concurrent rendering environments
to use a Lingui instance that is locale-specific, without risking global
Lingui to be switched to another locale.

In React, `<I18nProvider>` may be used to provide a locale-specific
Lingui instance, and it can be retrieved by using `useLingui`. After
that, the instance can be passed as argument to the `t` macro and
it will be used instead of the global instance, ensuring deterministic
behaviour.

This addresses concerns raised in https://github.com/lingui/js-lingui/issues/901, https://github.com/lingui/js-lingui/issues/578

Documentation, TypeScript definition changes and (more) tests are 
left to do,  but the main goal of this PR is to receive feedback on the 
approach and to see if this is on the right track.

## Example

<details><summary>Click to expand usage example</summary>

```tsx
import { I18n } from "@lingui/core";
import { t } from "@lingui/macro";
import { useLingui } from "@lingui/react";
import React, { FC, useCallback } from "react";
import * as Yup from "yup";
import { Field, Form, Formik } from "formik";

function buildYupValidationSchema(i18n: I18n) {
  return Yup.object().shape({
    // 3. Use the `t` macro to translate with the custom instance
    name: Yup.string().required(t(i18n)`Name is required`),
    description: Yup.string().required(t(i18n)`Description is required`),
  });
}

export const ExampleForm: FC = () => {
  // 1. Retrieve the i18n instance from the context
  const { i18n } = useLingui();

  // 2. Pass the i18n instance to functions that need it
  const validationSchema = buildYupValidationSchema(i18n);

  const handleSubmit = useCallback((values) => alert(JSON.stringify(values, null, 2)), []);

  return (
    <Formik
      initialValues={{ name: "", description: "" }}
      validationSchema={validationSchema}
      onSubmit={handleSubmit}
    >
      {({ isSubmitting }) => (
        <Form>
          <Field name="name" type="text" />
          <Field name="description" type="text" />
          <button type="submit" disabled={isSubmitting}>
            Submit
          </button>
        </Form>
      )}
    </Formik>
  );
};
```

</details>

### CODE REVIEW

**Comment by semoal** [comment]
Looks incredibly good Jeroen, not much more to say from my part that we should adjust TypeScript definitions and document this nicely and we're done for shipping this asap :)

**Comment by jeroenvisser101** [comment]
@semoal thanks! I was looking at the types, and found some time to add more documentation to them, along with usage examples that show up when using them in VSCode or other editors with language server integrations:

image

Let me know if there are parts where the wording may differ from the wording used in other places in Lingui, because that could cause confusion so I'd prefer to match them :)

I'll work on the documentation tonight 👍 

PS. I was also still thinking about an additional improvement, to allow a `t`-like macro that works like `defineMessage`, which would enable you to do: ```i18n._(dt`Hello ${world}`)```. It wouldn't differ much from ```defineMessage({message: `Hello ${world}`})```, and so I'll think about it a bit more, but if you have thoughts/ideas about it, I'm happy to hear them :)

**Comment by jeroenvisser101** [comment]
I think the docs are ready to go, they are short, but I also don't think a lot more is to be said about it. Going into it with examples may be useful, but I worried that they would be too specific to one implementation (e.g. React SSR) and not useful for other use-cases, maybe even misleading. Wdyt?

**Review by semoal — APPROVED** [review]

**Comment by semoal** [comment]
> I think the docs are ready to go, they are short, but I also don't think a lot more is to be said about it. Going into it with examples may be useful, but I'm worried that they would be too specific to one implementation (e.g. React SSR) and not useful for other use-cases, maybe even misleading. Wdyt?

We're good to go with the current documentation, I think creating an SSR example will too specific.

**Comment by semoal** [comment]
> PS. I was also still thinking about an additional improvement, to allow a t-like macro that works like defineMessage, which would enable you to do: i18n._(dt`Hello ${world}`). It wouldn't differ much from defineMessage({message: `Hello ${world}`}), and so I'll think about it a bit more, but if you have thoughts/ideas about it, I'm happy to hear them :)

Is not a bad idea, but probably making it that similar makes complex to understand our users what's the principal problem of t`` and why does defineMessage exist. Not sure about that, but if you think it's a good addition you can open an issue and we track if people is interested on this 👍 

Thanks for the hard-work mate, really appreciated

**Comment by jeroenvisser101** [comment]
Thanks! I'll consider the use case, maybe the `t(i18n)` will suffice for this use-case :)

**Comment by jeroenvisser101** [comment]
@semoal I think I may have messed up the typescript annotations, I'll look into it and open a follow up PR tonight, sorry for the hassle!

**Pull request merged**
