### PR TITLE
fix: extract works with template string id's

### PR DESCRIPTION
**Pull request by sultan99**
This PR closes issue #957 macro `t` with template string id.

### CODE REVIEW

**Comment by semoal** [comment]
Looks good mate, but could you me explain what does it mean?
`value?.quasis[0]?.value?.cooked`, just for giving context to the pull request

**Comment by sultan99** [comment]
@semoal `?` - It is an [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), so with `?` we don't get ReferenceError error if any value in the object will be undefined. I did it to cover all cases for the test coverage 😅.

**Comment by semoal** [comment]
> @semoal `?` - It is an [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), so with `?` we don't get ReferenceError error if any value in the object will be undefined. I did it to cover all cases for the test coverage 😅.
> 
> If you are asking about this object `value.quasis[0].value.cooked`, so the value in the template string is stored in that path and I had to get it in order to make it all work.

Yes, i was asking about the object quasis and the cooked value.  Also, another question, shouldn't be like this?:

```js
props[key.name] = (isIdLiteral && value?.quasis[0]?.value?.cooked) || value.value || undefined
```
When is a template literal always value.value it's undefined?
Just being sure that we don't break anything ^^

**Comment by sultan99** [comment]
Well, there is no big difference, but anyway I have optimized it.
Please check it & let's publish it! 🤘

**Pull request merged**
