### PR TITLE
Adds extractId option to conf

### PR DESCRIPTION
**Pull request by antonlyaptsev**
See problem in https://github.com/lingui/js-lingui/issues/402

### CODE REVIEW

**Comment by antonlyaptsev** [comment]
I'm going to add documentation this weekend

**Comment by antonlyaptsev** [comment]
Found bug with nested values. Fixing it

**Comment by antonlyaptsev** [comment]
> Found bug with nested values. Fixing it

Order of imports affects the result. It doesn't look good 😕 

```js
import { plural, select } from '@lingui/macro'
```
processes all the plurals first. Next, selects processing will get already processed plurals and `transformChoiceMethod` will assign `undefined` as a value.

Making
```js
import { select, plural } from '@lingui/macro'
```
fixes the problem

**Comment by antonlyaptsev** [comment]
@tricoder42 look at PR, please

**Comment by tricoder42** [comment]
@antonlyaptsev PR looks good! I just re-ran tests in AppVeyor, because there were some strange failures.

The ordering problem is annoying. Thanks for noticing though! I'm gonna tackle it in v3 macros, because I'm refactoring them anyway.

**Comment by antonlyaptsev** [comment]
@tricoder42 fixed these strange mocking failures 😈 
`macro` and `babel-plugin-transform-react` tests now pass

**Comment by deecewan** [comment]
i'm pretty keen to see this PR go through. I'd like to have my message IDs be a hash of the contents - that will remove duplicates, for a start (assuming the context is the same - hash should include that), and the translation service I use doesn't support overly long IDs or IDs with spaces, so I have to explicitly add an ID to every translation currently.

**Comment by tricoder42** [comment]
Hi @antonlyaptsev, sorry for delay. I'm not going to merge it to master, but rather to `next` branch which is the upcoming v3 release. There're many breaking changes, especially plugins are removed completely and replaced with macros.

I'm gonna keep this PR open until I cherry pick relevant changes to v3.

Thank you! 🙏

**Comment by tricoder42** [comment]
Just a note: In the next version I would like to minify IDs for production build:

```js
// source code
const msg = t`This is not a love song`
```

**generated output - development/extracting**

```js
const msg = /*i18n*/{
  id: "This is not a love song"
}

// Message file
{
  "This is not a love song": "Translation of a love song"
}
```

**generated output - production**

```js
const msg = "a"

// Message file
{
  "a": "Translation of a love song"
}
```

For a while I was thinking about moving `extractId` call invocation to CLI, when messages are extracted, but with message minification we could actually use it for our advantage:

```js
function getIdProp(props, file, defaultValue) {
    let id
    const config = getConfig()

    if (
      config.extractId &&
      typeof config.extractId === "function" &&
      !props.defaults
    ) {
      id = config.extractId(props, file)
    }

    if (id == null) id = defaultValue

    if (process.env.NODE_ENV === "production" && config.minifyId) {
        const idMap = loadIdMap()  // load map of IDs, so it's persistent across builds.
        id = minifyId(id, idMap)
    }

    return id
  }
```

I don't have specific plan how to do the minification yet, any suggestions welcome. I'm just writing this down to not forget it.

**Comment by stovmascript** [comment]
> especially plugins are removed completely and replaced with macros.

So changes added to `packages/babel-plugin-transform-react` should now be somewhere in `packages/macro`?

**Comment by tricoder42** [comment]
@stovmascript Yes, indeed. You need to do it on several places:
- JS macro - [replacePathWithMessage](https://github.com/lingui/js-lingui/blob/next/packages/macro/src/macroJs.ts#L44)
- JS macro - [processDescriptor](https://github.com/lingui/js-lingui/blob/next/packages/macro/src/macroJs.ts#L184)
- JSX macro - [replacePath](https://github.com/lingui/js-lingui/blob/next/packages/macro/src/macroJsx.ts#L56) (any occurence of t.stringLiteral(id))

Config is already loaded in macro, but you need to pass `extractId` value to each [transformer](https://github.com/lingui/js-lingui/blob/next/packages/macro/src/macroJsx.ts#L56)

**Comment by nathanforce** [comment]
I'd love to have this feature.  Is this PR still compatible after all this time?

**Pull request closed without merging**
