### PR TITLE
refactor: use useSyncExternalStore to subscribe for i18n updates

### PR DESCRIPTION
**Pull request by vonovak**
# Description

this refactors the change subscription mechanism used in Lingui React Provider to use the `useSyncExternalStore` hook, which according to [this](https://github.com/reactjs/rfcs/blob/main/text/0214-use-sync-external-store.md#summary) offers better support for "concurrent rendering features like selective hydration and time slicing". That being said, I'm not sure how exactly this should be better. Maybe someone will chime in and add more insight.

Everything should work the same except:

Previously, when the Provider was re-rendered with different i18n instance of different `defaultComponent`, it would ignore them. This likely never was an issue, but technically speaking, it was a bug. Now that is fixed. 

What I removed is detection of the cases when i18n.change would happen (catalog update, locale update) before the Provider subscribed for the change event. I removed the detection and a related test case, because I think it's a very unlikely scenario, but I can put it back if desired.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thekip** [comment]
don't have a react competency to review this one. If you think this would work better, i'll trust you.

**Review by andrii-bodnar — APPROVED** [review]
@vonovak thank you!

**Comment by thekip** [comment]
@vonovak this change increased size of react package from 2 kB to 2.27 kB due to some issue in the workflows it wasn't caught directly in this PR.  Could you increase a size limit budget, or re-consider the need of this change.

**Comment by vonovak** [comment]
hi @thekip,
I believe that there should be next to no effect on bundle size for people using React 18 because the useSyncExternalStore hook is shipped as part of the react package. For version 17 there is going to be some size increase there but it's likely that the `use-sync-external-store` shim will be installed by those users anyway.

I therefore don't see an issue with increasing the size budget at this point.

With regard for the need for this change, it's true that this change is not in response to some bug reported or something like that, it's more of a pre-emptive change with not-so-clear-necessity. I'll try to get another opinion on this diff.

**Comment by thekip** [comment]
@vonovak got your point, just increase bundle budget, please

**Comment by vonovak** [comment]
> @vonovak got your point, just increase bundle budget, please

can you send me a link to a pipeline that's failing or some more info about this? If you can't change the bundle budget, I'm not sure I'll be able to do it, I only have read rights here... Thanks :)

**Pull request merged**
