### PR TITLE
Raise an error when translation is missing

### PR DESCRIPTION
**Pull request by landsman**
change for edge case in issue: #544, for better debugging

### CODE REVIEW

**Comment by landsman** [comment]
Is there any progress about more talkative error messages? It's really pain for our guys.

**Comment by landsman** [comment]
@tricoder42 Is there any progress about more talkative error messages? It's really pain for our guys. Who is maintainer of CLI project? I am ready for help with this.

**Comment by tricoder42** [comment]
Hey @landsman, good point. I'll merge it but to the `next` branch. Lingui v3 should be released this or next week.

**Comment by landsman** [comment]
@tricoder42 Nice, this was just quick change. 
If you have any suggestions how to improve way to do it, I'll be glad to help.

**Comment by mdtusz** [comment]
This should probably throw an error, rather than just using `console.error` as it breaks the compile process and the message thrown can be a bit confusing if you don't know what to be looking for - it's just a stack trace.

My guess is that the majority of the time this issue arises when the translation keys between two catalog files don't match up as well, so adding a message to say "ensure all catalog files have consistent keys" or something could be helpful!

**Comment by landsman** [comment]
Hi guys, how this is looking? Can I help somehow?

**Comment by tricoder42** [comment]
Hey @landsman! Thanks for the PR! I've rebased it agains the latest `next` branch here 223ced96

**Pull request closed without merging**
