### PR TITLE
Feature/merge catalogs

### PR DESCRIPTION
**Pull request by johnparn**
Use case: in a project with multiple packages, each package will handle the translation themselves, ie each package will for example have a `cs.po` and a `en.po` file.

However, when integrating the packages in an app, we would like to just have two compiled files to care about. So this PR contains functionality to specify the configuration option `mergePath`. During compilation the messages are merged and saved to  `mergePath`.

For example if `mergePath` is assigned `<rootDIR>/locales/{locale}` catalogs will be compiled to `/locales/cs.js` and `/locales/en.js`.

Yes, at the moment translations may overlap if they use the same key. And the last read message will override previous one with the same key.

### CODE REVIEW

**Comment by tricoder42** [comment]
Looks pretty good! I'm gonna review it soon! Thank you very much

**Comment by tricoder42** [comment]
Hey @johnparn, I apologize for such a long delay. Are you still interested in working on this PR? If so, could you please merge latest `next` branch and resolve conflicts?

**Comment by johnparn** [comment]
I’m rather busy right now and the upcoming weeks. But I’ll see if I can squeeze it in.

**Comment by tricoder42** [comment]
@johnparn No worries. This issue doesn't block v3 release. We can ship it in 3.1 anytime.

Thank you for your time and efforts!

**Comment by johnparn** [comment]
Superseded by new PR #658. Closing this issue.

**Pull request closed without merging**
