### PR TITLE
feat: memoizable react translations

### PR DESCRIPTION
**Pull request by vonovak**
# Description

this is an improvement for #1690 (https://github.com/lingui/js-lingui/issues/1690#issuecomment-1592879371), addresses difficulty with the current api: https://lingui.dev/tutorials/react-patterns#memoization-pitfall

I'm opening this for feedback; after potential issues are addresses, I can write docs.

This allows the following construct to work correctly:

```tsx
import { msg } from "@lingui/macro";

export const WelcomeMsg = () => {
  const { _ } = useLingui();

  const memoizedWelcome = useMemo(() => {
    return _(msg`Welcome`);
  }, [_]);

  return <Text>greeting: {memoizedWelcome}</Text>;
}
```

It feels like there are a lot of ways to achieve more or less the same thing now, with `t` macro, `Trans`, `msg`... I think it's okay to add this, if there are quality docs.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by niksauer — APPROVED** [review]
Exactly what we need ❤️

**Comment by thekip** [comment]
By the way, i also thought about making something like that as default solution in docs instead of using global `t` macro which is known as error-prone.  I thought to make it more explicit: 

```tsx
import { t } from "@lingui/macro";

// ❌ Bad because there no direct relation between `t` and `useLingui`
export const WelcomeMsg = React.memo(() => {
  useLingui();
  return <Text>greeting: {t`Welcome`}</Text>;
});
```

```tsx
import { t } from "@lingui/macro";

// ❌ Better than first one, but still bad because too verbose, 
//  and Developers can omit `(i18n)` part and don't get consequences immediately
export const WelcomeMsg = React.memo(() => {
  const { i18n } = useLingui();
  return <Text>greeting: {t(i18n)`Welcome`}</Text>;
});
```

So I thought about implementing a new macro `useLingui`: 

```tsx
import { useLingui } from "@lingui/macro";

// ✅ Good, as you see direct dependecy on the hook, 
//    but really hard to implement from Transpilation point of view
export const WelcomeMsg = React.memo(() => {
  const { t } = useLingui();
  return <Text>greeting: {t`Welcome`}</Text>;
});
```

But thought about that once again and i also came to similar to yours solution, that instead of creating new complicated macro we can achieve the same result with existing code. We only need to change documentation to encourage people to use different methods: 

```tsx
import { useLingui } from "@lingui/macro";

export const WelcomeMsg = React.memo(() => {
  const { i18n } = useLingui();

  // expand macro and mark message for extraction with `msg`
  return <Text>greeting: {i18n.t(msg`Welcome`)}</Text>;
});
```

Despite the fact, we came to here solving diffrent issues, we end up with a similar solution. 
As a further steps i think we need to replace all usages and mentions of global `t` macro to `_(msg)` in React context in docs.

**Comment by vonovak** [comment]
> As a further steps i think we need to replace all usages and mentions of global t macro to _(msg) in React context in docs.

@thekip so just to make sure I understand :)
you'd use the code from this PR and recommend write code as in these examples?

(I changed the examples to use `<Button title={...} />` because for the previous examples, using `<Trans />` would be better :) )


```tsx
import { msg } from "@lingui/macro";

export const WelcomeMsg = () => {
  const { _ } = useLingui();

  return <Button title={_(msg`Do something`)} />
}
```

or in case someone needs to use memo:

```tsx
import { msg } from "@lingui/macro";

export const WelcomeMsg = () => {
  const { _ } = useLingui();

  const memoizedTitle = useMemo(() => {
    return _(msg`Do something`);
  }, [_]);

  return <Button title={memoizedTitle} />
}
```


I really like this one that you suggested, thought about it as well, but I don't think I have the bandwidth to explore the transpilation :/

```tsx
import { useLingui } from "@lingui/macro"; // or "@lingui/react"?

// ✅ Good, as you see direct dependency on the hook, 
//  but really hard to implement from Transpilation point of view
export const WelcomeMsg = () => {
  const { t } = useLingui();
  return <Button title={t`Do something`} />
}
```

which would transpile to this?

```tsx
import { useLingui } from "@lingui/react";

export const WelcomeMsg = () => {
  const { t } = useLingui();
  return (
    <Button
      title={t(
        /*i18n*/ {
          id: "some_hash",
          message: "Do something",
        },
      )}
    />
  );
};
```

**Comment by thekip** [comment]
> you'd use the code from this PR and recommend write code as in these examples?

@vonovak yes, exactly. 

Regarding new macro: 

```ts
import { useLingui } from "@lingui/macro"; // or "@lingui/react"?

export const WelcomeMsg = () => {
  const { t } = useLingui();
  return <Button title={t`Do something`} />
}
```

This ideally should be transpiled to something like

```ts
import { useLingui } from "@lingui/macro"; // or "@lingui/react"?

export const WelcomeMsg = () => {
  const { i18n } = useLingui();
  return <Button title={i18n._(`<expanded macro>`)} />
}
```

So to achieve this we need to find all usages of `t` than traverse scope upper and somehow identify boundaries of react component, then find in the react component `useLingui()` call and rewrite it.  or it could be done vice versa, from hook down to the usages. There could be so many edge cases and still problems with memo because you could not refer to `t` as a dependency in runtime.  Also, someone may want to pass `t` function as parameter somewhere expecting this to work. 

So i prefer may be less elegant but more future-proof solution.

**Comment by vonovak** [comment]
> This ideally should be transpiled to something like

I believe the transpilation result you gave would be more complicated than needed because it transforms `const { t } = useLingui();` to `const { i18n } = useLingui();`, and if there is a `useMemo` such as in the following example, we'd need to transform hook dependencies as well...

```tsx
import { useLingui } from "@lingui/macro"; // or "@lingui/react"?

export const WelcomeMsg = () => {
  const { t } = useLingui();

  const greeting = useMemo(() => {
    return t`hello world`
  }, [t]);

  return <Button title={greeting} />
}
```

Anyhow, let me wrap this up, I'll add the docs for what I added here and then mark as ready for review :)

**Review by thekip — APPROVED** [review]

**Comment by vonovak** [comment]
@andrii-bodnar can you please review / merge? I have some other stuff in the pipeline and would like to get this merged first, thanks :)

**Review by andrii-bodnar — APPROVED** [review]
@vonovak thank you!

Sorry for the late response 🙏

**Pull request merged**
