### PR TITLE
feat: enable importAttributes and explicitResourceManagement for extractor

### PR DESCRIPTION
**Pull request by timofei-iatsenko**
# Description

Enable `importAttributes` and `explicitResourceManagement` parser plugins, because they are stage3 now and should be supported out of the box by lingui extractor

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Examples update

Fixes https://github.com/lingui/js-lingui/issues/2003

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Review by andrii-bodnar — APPROVED** [review]

**Comment by timofei-iatsenko** [comment]
@andrii-bodnar rebased

**Comment by andrii-bodnar** [comment]
@timofei-iatsenko the CI has failed, please check - https://github.com/lingui/js-lingui/actions/runs/10980398987/job/30486125563?pr=2009

**Comment by vonovak** [comment]
Just wondering, is this a preparation for future use of these features or what's the reason for this? I assume this doesn't influence consumers in any way, it's just for the tooling that's included in the lingui cli?

**Comment by timofei-iatsenko** [comment]
We stated in the docs that lingui extractor should understand out of the box valid ecmascript  + stage3 features. It's written [there](https://lingui.dev/guides/message-extraction#supported-source-types:~:text=The%20extractor%20supports%20TypeScript%2C%20Flow%20and%20JavaScript%20(Stage%203)%20out%20of%20the%20box.) 

These 2 features became stage3 recently and our extractor fail on them but should not.

**Comment by timofei-iatsenko** [comment]
@andrii-bodnar all checks are green. Could be merged and deplyed in v4. Apologize that this took so long to finish.

**Pull request merged**
