### PR TITLE
Review react-patterns for v3

### PR DESCRIPTION
**Pull request by vonovak**
the diff looks big, but it's just because I moved things around a little

edit: there is a lot of talk about automatic message ids (taken from the translations) vs custom message IDs. What I'm missing is a discussion about why I would like to use one over the other..? Listing some pros and cons would be nice.

### CODE REVIEW

**Comment by tricoder42** [comment]
Pretty good! I'll take a look in the morning! Thanks a lot! 👍

**Comment by tricoder42** [comment]
> there is a lot of talk about automatic message ids (taken from the translations) vs custom message IDs. What I'm missing is a discussion about why I would like to use one over the other..? Listing some pros and cons would be nice.

Good idea! I was thinking about writing such summary, but last time I used custom keys was about 3 years ago and I barely remember why we did it. It would be great to collect feedback from other developers, why they do it.

Anyway, I fixed one line, but everything else looks super good! Thanks a lot!

**Comment by vonovak** [comment]
thanks for the fix. One thing I'm wondering now - we use js-lingui in a project that is english-only now, can I ask you about one thing?

Let's say I have `<Trans>New</Trans>` in several places and this gets extracted like this:

```
  "New": {
    "translation": "",
    "origin": [
      [
        "file.js", 58,
        "file2.js", 158
      ]
    ]
  },
```

Let's say I want to translate this to Czech and I find out that in one place, I want this translation to be "Nový" and in another place this should be "Nová" (or "Nové" / "Nově"...) (for non-Czech speakers: http://www.locallingo.com/czech/grammar/adjectives_declension_masc.html).

What would be the way to go about this? I think this would be nice to cover as well (I'm okay with covering that once I know the right answer). Thanks!

**Comment by tricoder42** [comment]
[Project Fluent](https://projectfluent.org/fluent/guide/variants.html) uses variants to solve this. I think we're limited by ICU MessageFormat syntax here, but the easiest workaround would be define a different message for each usecase:

```jsx
<Trans id="New-nominative">New</Trans>
```

In most cases, you should translate whole sentence, but in cases when you need a single word, I think this is the only way to go...

**Comment by FredyC** [comment]
ICU does not handle this, but PO format does with context which we talked about already. This is a nice use case for it, but truthfully it would end up with something like `<Trans ctx="home-page">New</Trans>` which isn't much shorter. And using `i18n` directly would be even more bloated most likely.

**Pull request merged**
