### PR TITLE
docs: add Crowdin tool

### PR DESCRIPTION
**Pull request by andrii-bodnar**

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
cc @khrystynabfromcrowdin

**Comment by tricoder42** [comment]
Hey @andrii-bodnar, looks good. Could you also please add a short setup guide how to use Lingui CLI with Crowdin? Similar to this section https://github.com/lingui/js-lingui/blob/main/docs/tools/translation-io.rst#installation

**Comment by andrii-bodnar** [comment]
Hi @tricoder42, thanks, I will look into this

**Comment by andrii-bodnar** [comment]
@tricoder42 done ✅

**Comment by tricoder42** [comment]
Looks good to me 👍 Thank you!

**Pull request merged**
