### PR TITLE
Update react-native.rst

### PR DESCRIPTION
**Pull request by vonovak**

### CODE REVIEW

**Comment by tricoder42** [comment]
Ups, I totally missed that! Is it possible to use [Intl polyfill](https://github.com/andyearnshaw/Intl.js/)?

**Comment by vonovak** [comment]
> Is it possible to use Intl polyfill?

yeah, that's a fair point, that should work too. Google says it should work. Let me add that.

**Comment by tricoder42** [comment]
I also want to check if it's possible to load this polyfill automatically in message catalogs... that would be even better. But go ahead, add it here and I'll mention polyfill in other docs (react, js)

**Comment by vonovak** [comment]
@tricoder42 done. Really good job on the library, btw! I also like the improved docs, makes it much easier for newcomers to start using the lib.

**Comment by tricoder42** [comment]
Nice! Thank you very much for keeping this tutorial updated!

**Comment by tricoder42** [comment]
If you had an intereting idea for react-native application, which is simple enough to be an example, but complex enough to cover all features of lingui, let me know :) I would like to add a react-native app to examples, so it's part of testing suit.

**Pull request merged**
