### PR TITLE
first pass at vanilla js docs

### PR DESCRIPTION
**Pull request by vonovak**
hi @tricoder42 this is a very first attempt at what could become a the plain-js docs page.

One thing that I'd like to know is - is `setupI18n` intended to be imported and called, or should a developer be importing the i18n object from `@lingui/core` and call the `load` and `activate` functions like [here](https://github.com/lingui/js-lingui/blob/0d0aa92e334909a27ec0a38b2c99559e3c4558e5/packages/core/src/i18n.js#L207)?

Calling `setupI18n` would create multiple instances of i18n object, possibly leading to some bugs if the developer doesn't handle the imports right.

### CODE REVIEW

**Comment by tricoder42** [comment]
Super awesome! Good job 🎉

**Comment by vonovak** [comment]
Hi @tricoder42, thanks for merging. Can you please answer the question I had about setupI18n? I'm curious to know why recommend calling setupI18n multiple times VS using the load and activate functions. Thanks!

**Comment by tricoder42** [comment]
@vonovak sorry, I missed that question.

Default i18n object is useful only when you don’t have any special requirements. Sometimes it may be enough just to import it and start translating.

setupI18n factory is useful when you need custom or isolated instance of i18n object.

I think the default export could be removed in future versions in favor of setupI18n, but that’s for next major version...

**Comment by vonovak** [comment]
so I'm wondering, is this going to be released? :) Thanks.

**Comment by tricoder42** [comment]
It's live now! https://lingui.github.io/js-lingui/tutorials/javascript.html

I have to fix the auto deployment script, for some reason it doesn't work on CI...

**Comment by vonovak** [comment]
thanks, will work on react native docs next

**Comment by tricoder42** [comment]
Awesome!

**Comment by snegostup** [comment]
Guys may I ask you to include examples with custom IDs too. Not seeing how to use IDs can frustrate and turn away a lot of people.

**Pull request merged**
