### PR TITLE
refactor(macro): split js (core) and jsx (react) macro

### PR DESCRIPTION
**Pull request by thekip**
https://github.com/lingui/js-lingui/issues/1361

@Martin005 @andrii-bodnar please take a look here. I want to get feedback before i continue.

Overview: 
```mermaid
graph LR
    core("@lingui/core/macro") --> lib("@lingui/macro-lib")
    react("@lingui/react/macro") --> lib
    macro("@lingui/macro") --> react
    macro --> core

```

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Looks interesting, but I don't really like the nascence of the new package, can we avoid it? Previously we discussed it and agreed that it was possible

**Comment by thekip** [comment]
> Looks interesting, but I don't really like the nascence of the new package, can we avoid it? Previously we discussed it and agreed that it was possible

No. Look at the graph i wrote in the description. 

Why you so don't like introducing new packages? It's the way how it works.  It's internal and nobody should care. 
Look at the [formatjs](https://github.com/formatjs/formatjs/tree/main/packages) or [jest](https://github.com/facebook/jest/tree/main/packages) packages.

**Comment by andrii-bodnar** [comment]
Sure, I saw the graph. I can't say that I don't like new packages, but I prefer not to introduce new "entities" if possible and there is no urgent need

If it's inevitable, it'll be so 🤷‍♂️

**Comment by andrii-bodnar** [comment]
The most I worrying here is the potential `@lingui/code` bundle size increase

**Comment by thekip** [comment]
There would be no bundle size increase (the macro is not bundled), but installation size of `@lingui/core`and `@lingui/react` would increase. For users who use macro nothing will be changed, installation size of all packages would be the same. For users who not using macro - yes, now macro and babel are always installed. But frankly speaking, i would not worry too much about non-macro usage, the main use case is with macro and we should concentrate our effort to make it highly polished.

**Comment by thekip** [comment]
i don't know why, but i don't like what happened here 😬

We indeed need to split macro for different frameworks, but the idea that all babel dependencies would be installed even if you are not using them makes me nervous. 

Also i don't understand how we should organize tests in the repo. Now they live in one place, and we have cases where jsx + and js macro tested together. How this should be done after split i don't know.

**Comment by andrii-bodnar** [comment]
Let's postpone it to the future major release (v5 or v6), maybe later we will have a better understanding of how to properly do this

**Pull request closed without merging**
