### PR TITLE
import setupI18n from core

### PR DESCRIPTION
**Pull request by dominikdosoudil**
import `setupI18n` from `@lingui/core` instead of `@lingui/react`

(`setupI18n` not found in `@lingui/react`)

### CODE REVIEW

**Comment by tricoder42** [comment]
Hey, thanks for the PR. Could you please rebase it against `next` branch? That should be the place with latest migration docs.

**Comment by dominikdosoudil** [comment]
@tricoder42 yep, sure. (That's what I've been thinking about, but the "Edit on GitHub" took me to `master`.)

**Comment by dominikdosoudil** [comment]
When I am looking into the next migration guide, I am kinda confused. It's recommended to use default `i18n` instance instead of `setupI18n`. However it was giving some type errors when passing into I18nProvider as i18n prop. Using latest core and react. I'll need to look into it more deeply. This PR is probably wrong, sorry

**Comment by tricoder42** [comment]
No worries. In the v3 your indeed advised to use the default `i18n` instance, but you can also use a custom one. Feel free to reach me if you need anything

**Pull request closed without merging**
