### PR TITLE
refactor: minor improvements to RSC

### PR DESCRIPTION
**Pull request by vonovak**
# Description

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

This is a refactor of the recently added RSC functionality. It makes some small changes:

1) memory efficiency: previously, every call  to `useLingui` and `TransRsc` would allocate memory. With this change, the necessary memory is allocated once (well, depends on how many times `setI18n` is called, but it won't be much) for each request and reused across all `useLingui` and `TransRsc`
2) it appears `defaultComponent` was not considered by RSC so I added it. I still need to test it but if we ignore it, I'm afraid some users would get hydration mismatches

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Examples update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thekip** [comment]
> memory efficiency: previously, every call to useLingui and TransRsc would allocate memory. With this change, the necessary memory is allocated once (well, depends on how many times setI18n is called, but it won't be much) for each request and reused across all useLingui and TransRsc

I don't get this one. Do you think that returning `.current` directly from `getI18n` will do additional allocates? Why?

**Comment by vonovak** [comment]
it's not a huge deal, but memory is allocated [here](https://github.com/lingui/js-lingui/blob/5d9845a63d8141db92af2f6f395b932eabe29f5c/packages/react/src/TransRsc.tsx#L14) and [here](https://github.com/lingui/js-lingui/blob/5d9845a63d8141db92af2f6f395b932eabe29f5c/packages/react/src/index-rsc.ts#L20)

**Review by andrii-bodnar — APPROVED** [review]

**Comment by thekip** [comment]
Got it, there are new object creations. So it's not related to `.current` returned from `getI18n`.
 So could we return `.current` directly as it was before? I'm expecting that `getI18n` could be used actively, since it's the only way to get i18n in RSC context. I believe it would be a better API if user will not have to call `.current` every time.

**Comment by vonovak** [comment]
Haha, yeah, that makes sense. Good catch, I did that.

**Review by thekip — APPROVED** [review]

**Pull request merged**
