### PR TITLE
fix(cli): avoid crashing when adding custom extractors without default exports

### PR DESCRIPTION
**Pull request by j4hr3n**
# Description

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@j4hr3n is it still a draft?

**Comment by thekip** [comment]
@j4hr3n could you provide a code sample reproducing the issue? I've checked the code flow and don't understand in which circumstances that could be possible.

**Comment by j4hr3n** [comment]
> @j4hr3n could you provide a code sample reproducing the issue? I've checked the code flow and don't understand in which circumstances that could be possible.

@thekip @andrii-bodnar I posted about this on Discord. 

I created an example repo where it can be reproduced here: https://github.com/j4hr3n/vue-lingui-ts

https://discord.com/channels/974702239358783608/974704045346394172/1105412244252151889

**Comment by thekip** [comment]
@j4hr3n i've checked your example. You need to just update to latest version. There was [an issue](https://github.com/lingui/js-lingui/issues/1648) with this import `import { extractor as babelExtractor } from "@lingui/cli/api";` now it's fixed

**Pull request closed without merging**
