### PR TITLE
fix(macro types): mark `other` as required for ChoiceOptions

### PR DESCRIPTION
**Pull request by taozhou-glean**
# Description

`other` should be required for choice macros, and looks like we do have it as required for `SelectOptions`, `SelectChoiceProps`  and `PluralChoiceProps`, just not `ChoiceOptions` which is probably not intended.

and ICU message without `other` may be invalid:

image

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thekip** [comment]
You need also add a test in `packages/macro/__typetests__/index.test-d.tsx`

**Comment by taozhou-glean** [comment]
> You need also add a test in `packages/macro/__typetests__/index.test-d.tsx`

done! thanks

**Comment by taozhou-glean** [comment]
> > You need also add a test in `packages/macro/__typetests__/index.test-d.tsx`
> 
> done! thanks

BTW, `yarn test:tsd` is failing with 3 tests on `t({})` above for me, checked upstream/next and same there. @thekip

**Comment by thekip** [comment]
`yarn release:build` before `yarn test:tsd` it's a known issue, building modern application with monorepo is hard. 

I'm currently looking for another solution.

**Comment by taozhou-glean** [comment]
> yarn test:tsd

test all passed now! maybe just update scripts for `test:tsd` to always run `release:build` before as a workaround for now

**Comment by thekip** [comment]
in github WF it's already done this way. In development, it doesn't bother me so much. And i actually find it more useful to have faster feedback when working on typings, so i'm running build once and then re-run only tests.

**Review by thekip — APPROVED** [review]

**Review by andrii-bodnar — APPROVED** [review]

**Pull request merged**
