### PR TITLE
bug: wrong plural handling in v4

### PR DESCRIPTION
**Pull request by vonovak**
# Description

this PR provides a test case that passes but should fail

unfortunately, I don't have time to fix this, just letting you know, maybe you can take the test case and fix yourself

maybe this is expected. I think it actually might be the correct behavior, in which case I can document it, let me know

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thekip** [comment]
Why do you think it should not pass? The underlying plural rule is resolved to `one`

```js
(new Intl.PluralRules('en-GB')).select(-1); // => 'one'
```

**Comment by andrii-bodnar** [comment]
https://format-message.github.io/icu-message-format-for-translators/editor.html

test

**Comment by vonovak** [comment]
yes, so that means it's expected, but probably not documented anough.

my expectation was that

```
        <Plural
          value={-1}
          zero={'There are no books'}
          one={"There's one book"}
          other={'There are # books'}
        />
```

would not render `There's one book` but it does render that. We need to clarify that the `one` prop (and other) do not correspond to the number passed in `value` but to result of `Intl.PluralRules`

**Comment by thekip** [comment]
In the docs written that these props are plural categories, not exact matches. 

These plural categories are defined for each language by CLDR. Keep in mind that `one` doesn't correspond to only ==1, but it may correspond to different numbers such as 21, 31, and so on.

If you want to specify an exact match - there is a special semantics for that: 

```tsx
import { Plural } from "@lingui/macro"

<Plural
    value={count}
    offset={1}

    // when value == 0
    _0="Nobody arrived"

    // when value == 1
    _1="Only you arrived"

    // when value == 2
    // value - offset = 1 -> `one` plural form
    one="You and # other guest arrived"

    // when value >= 3
    other="You and # other guests arrived"
/>
```

**Pull request closed without merging**
