### PR TITLE
hotfix: i18n props and exported component

### PR DESCRIPTION
**Pull request by semoal**

### CODE REVIEW

**Review by tricoder42 — APPROVED** [review]

**Comment by tricoder42** [comment]
Pretty good! Thanks 👍

**Comment by renchap** [comment]
Sorry I did not had time to have a look faster than @tricoder42 but I think you also need to export the type `withI18nProps` so TS users can use it (like in version 2)

**Comment by tricoder42** [comment]
@renchap It is exported https://github.com/semoal/js-lingui/blob/b31883adf762db73866a7550701b916f89eacc39/packages/react/src/I18nProvider.tsx#L51

Maybe we could keep the `export` on the same line as a type (I missed that), but functionaly it's ok 👍

**Comment by renchap** [comment]
I missed this line, all is fine then 🙂

**Pull request merged**
