### PR TITLE
[next] Add support for FLUENT format

### PR DESCRIPTION
**Pull request by nodkz**
According to https://github.com/lingui/js-lingui/issues/489#issuecomment-497781933 needs to implement:
- [x] format in `cli`
- [x] processToken in `macro`
- [ ] add config property `parser`
- [ ] check compile
- [ ] polishing & refactoring

### CODE REVIEW

**Comment by nodkz** [comment]
@tricoder42 
- need some help with introducing `parser` option to config
- need some info on how to compile phase works

**Comment by tricoder42** [comment]
@nodkz How can I help?

**Comment by nodkz** [comment]
@tricoder42 please add `parser` option as you noted here https://github.com/lingui/js-lingui/issues/489#issuecomment-497781933 

How I saw it will require a small code refactoring. And will be better if you make it.
For me it quite difficult to fix all places where new `parser` option will be used. How I understood it should be applied to babel-extractor and cli-compiler.

I added [macro/fluent.ts](https://github.com/lingui/js-lingui/pull/531/files#diff-69886d92ee256176ca66cf8809a99389) but it is no way to use in the code yet.

**Comment by tricoder42** [comment]
I'm on it. What if we name it `messageFormat` instead of `parser`? While `parser` is technically valid name, I find `messageFormat` more descriptive.

**Comment by nodkz** [comment]
@tricoder42 I'm agree. messageFormat is the better name

**Comment by tricoder42** [comment]
Hey @nodkz, this PR seems to be stale and new major release has just been published. If you'd like to finish it, please rebase it against `main` branch and reopen. Thanks for your efforts! 👍

**Pull request closed without merging**
