### PR TITLE
chore: update node in ci

### PR DESCRIPTION
**Pull request by vonovak**
# Description

For many of the CI jobs we're using Node 16 which has gotten quite old now.
I updated some jobs to using node LTS (where it's unlikely those jobs would break when the LTS version changes), and bumped some other ones to an explicit node version so that we have the version under our control.

## Types of changes

[//]: # (What types of changes does your code introduce to Lingui?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

Fixes # (issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/lingui/js-lingui/blob/main/CODE_OF_CONDUCT.md) docs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Currently, we have the node 16 version [specified in the `package.json`](https://github.com/lingui/js-lingui/blob/main/package.json#L38). Shouldn't the CI be locked to this except for tests for other versions?

**Comment by Kepro** [comment]
btw you can also update `setup-node` and `checkout` to v4 both :-) (or also use dependabot to keep actions and packages up todate)

**Comment by vonovak** [comment]
hello, to expand on the description: the idea of this PR is not to introduce any potentially breaking change, so the minimum supported node version should stay at 16, and the test suite (main-suite.yml) still runs the tests on node 16. AFAICT that should be enough to know node 16 is kept working but please correct me if I'm wrong.

For other suites such as docs testing and publishing I did bump the node version that they run on, but that doesn't influence the library consumers in any way.
One job where we could see a change in behavior although it seems not very likely imho is the `release.yml` job. I'm happy to revert the changes there, please let me know.

To wrap up, the goal here was to make sure we know everything works on newer versions of node because our pipelines did no cover that. As it turns out, there was a problem on Windows. This is now fixed :) One extra things we could do is add node 21 to the test matrix too.

**Review by andrii-bodnar — APPROVED** [review]
@vonovak thank you!

**Pull request merged**
