### PR TITLE
Fixes --config option processing

### PR DESCRIPTION
**Pull request by brandonc**
### Overview

Processing process.argv inside getConfig can cause problems when used in conjunction with @lingui/loader since the --config arg is also used by webpack

Instead of processing process.argv, getConfig now accepts the path to a custom config file. Each command now passes the config option from commander into getConfig. Webpack loader now accepts an option "config" that can be used to specify a config file.

### Notes

Should all lingui options be allowed via webpack loader options? loader could be modified to assign all options to getConfig output.

I think I fixed an unrelated bug with lingui/loader. compileNamespace and pseudoLocale config options  were not being passed to createCompiledCatalog, so I assume that all loader compiled output was being exported as cjs.

### Testing

I smoke tested the fix by implementing lingui/loader with a config option while simultaneously using the --config option with webpack. I also verified that `lingui extract --config` continued to function as expected.

### CODE REVIEW

**Comment by brandonc** [comment]
@tricoder42 Thanks! What is the next step?

**Comment by tricoder42** [comment]
Sorry I completely forgot. I'll release it in few minutes.

**Comment by tricoder42** [comment]
Released in [v2.8.2.](https://github.com/lingui/js-lingui/releases/tag/v2.8.2)

**Comment by semoal** [comment]
Hi guys actually my code is crashing due this release.
Captura de pantalla 2019-05-22 a las 22 46 16

Any suggerence? @tricoder42

**Comment by tricoder42** [comment]
@semoal Sorry for that. The tests for loader are broken, so this bug sneaked into the release :/

I'll fix it in few minutes.

**Comment by tricoder42** [comment]
@semoal Fixed in [v2.8.3](https://github.com/lingui/js-lingui/releases/tag/v2.8.3). Thanks for report!

**Pull request merged**
