### PR TITLE
docs(examples): update examples

### PR DESCRIPTION
**Pull request by thekip**
# Description

- nextjs-babel - updated, issues with SSR fixed, best practices implemented
- nextjs-swc - created, it's diffrent than in SWC repo and differs from nextjs-babel just to show more concepts
- js - deps updated
- create-react-app - updated, fixed incompatibilities with react-scripts@v5

https://github.com/lingui/js-lingui/issues/1393

### CODE REVIEW

**Review by andrii-bodnar — APPROVED** [review]

**Comment by tanwarvinay** [comment]
Is there any workaround to this ? Translations are not added to HTML on server. They are being added on Client Side.

**Comment by thekip** [comment]
@tanwarvinay check the latest examples in the repository **carefully**, it's working perfectly with SSR

**Comment by tanwarvinay** [comment]
@thekip Thank you for the quick response. On my localhost i actually get translations on SSR but when i deploy my code on staging server than the poblem occurs. 
 I am also getting consistently following warning on my localhost --> 

> I18nProvider rendered `null`. A call to `i18n.activate` needs to happen in order for translations to be activated and for the I18nProvider to render.This is not an error but an informational message logged only in development.


My Implementation Example

```
./I18nProviderWrapper.js. // used in _app.js

import { useSelector } from 'react-redux';
import { i18n } from '@lingui/core';
import { I18nProvider } from '@lingui/react';

import {
  loadLocales,
} from '~/i18n/utils/loadLocales';

const I18nProviderWrapper = ({ children }) => {
  const locale = useSelector((state) => state.globalData.locale);
  loadLocales(locale);
  return (
    <I18nProvider i18n={i18n} >
      {children}
    </I18nProvider>
  );
};

export default I18nProviderWrapper;

```
```
./loadlocales.js
import { i18n } from '@lingui/core';

export const loadLocales = async (locale) => {
  const { messages } = await import(
    `~/i18n/translations/${locale || 'en'}/messages.js`
  );
  i18n.load(locale, messages);
  i18n.activate(locale);
};

```

The Above Code Works perfectly on my localhost (on build also) but gives the above stated warning. But does not work when staging server is used.

**Comment by andrii-bodnar** [comment]
@gpessa please make sure that the Lingui `core` and `react` packages are located in the `dependencies` and not in `devDependencies`

**Comment by thekip** [comment]
@tanwarvinay please use examples provided in this repo. Your integration is wrong. `loadLocales` in your case is async and not awaited anyhow in the react components, this is the root of your issue. The examples in the repo have full solution which battle tested on production on many websites.

**Comment by tanwarvinay** [comment]
@andrii-bodnar and @thekip you are a life saver. Thank you so much.

**Pull request merged**
